import type { Domain, GlossaryTermInput } from "@/lib/curriculum";

type T = [slug: string, term: string, domain: Domain, definition: string, topicIds: string[], prerequisites?: string[], seniorNote?: string];

const term = ([slug, name, domain, definition, topicIds, prerequisites = [], seniorNote]: T): GlossaryTermInput => ({
  slug,
  term: name,
  domain,
  definition,
  topicIds,
  prerequisites,
  ...(seniorNote ? { seniorNote } : {}),
});

/** Terminology added with the expanded curriculum: SQL, cloud, GenAI and the rest of the stack. */
const TERMS: T[] = [
  // Foundations
  ["recursion", "Recursion", "foundations", "A function that solves a problem by calling itself on a smaller version of the same problem until it reaches a base case.", ["w01-d02-recursion-call-stack"], [], "Every recursive call adds a stack frame; Python's default limit is about 1,000 frames, so deep recursion is often rewritten as a loop."],
  ["call-stack", "Call stack", "foundations", "The stack of active function calls; each call pushes a frame with its local variables and pops it when it returns.", ["w01-d02-recursion-call-stack"], ["recursion"]],
  ["vectorization", "Vectorization", "foundations", "Applying an operation to a whole array at once instead of looping element by element, usually running in fast compiled code.", ["w01-d01-python-r-idioms", "w01-d04-dataframe-wrangling"]],
  ["dataframe", "DataFrame", "foundations", "A table of named columns, each holding one type, used by pandas, polars and R's data.frame for data analysis.", ["w01-d04-dataframe-wrangling"]],
  ["tidy-data", "Tidy data", "foundations", "A layout where each variable is a column, each observation is a row and each type of observational unit is a table.", ["w01-d04-dataframe-wrangling"], ["dataframe"]],
  ["random-seed", "Random seed", "foundations", "A starting value for a pseudo-random generator so the same 'random' numbers come out on every run.", ["w01-d03-testing-reproducibility"], ["reproducibility"]],

  // Data structures and algorithms
  ["linked-list", "Linked list", "dsa", "A chain of nodes where each node points to the next, giving O(1) insertion at a known position but O(n) access by index.", ["w03-d05-linked-lists"], ["big-o"]],
  ["stack", "Stack", "dsa", "A last-in, first-out collection: you push onto the top and pop from the top.", ["w04-d01-stacks-queues-heaps"]],
  ["queue", "Queue", "dsa", "A first-in, first-out collection: items join at the back and leave from the front.", ["w04-d01-stacks-queues-heaps"]],
  ["monotonic-stack", "Monotonic stack", "dsa", "A stack kept in increasing or decreasing order, used to find the next greater or smaller element in linear time.", ["w04-d01-stacks-queues-heaps"], ["stack"]],
  ["binary-search", "Binary search", "dsa", "Finding a target in sorted data by repeatedly halving the range, in O(log n) steps.", ["w04-d04-binary-search-backtracking"], ["big-o"], "Also works on any monotonic yes/no question, such as the smallest capacity that ships packages in d days."],
  ["two-pointers", "Two pointers", "dsa", "Moving two indexes through a sequence, often from both ends or at different speeds, to avoid nested loops.", ["w03-d02-sliding-window"], ["big-o"]],
  ["bst", "Binary search tree", "dsa", "A binary tree where every node is larger than all keys in its left subtree and smaller than all keys in its right subtree.", ["w04-d01-trees-bst-tries"], ["binary-search"], "Operations are O(height); balanced variants (red-black, AVL, B-trees) keep the height O(log n)."],
  ["trie", "Trie", "dsa", "A tree of characters where each path from the root spells a prefix, making prefix lookups fast.", ["w04-d01-trees-bst-tries"]],
  ["union-find", "Union-find", "dsa", "A structure that tracks which items are in the same group and can merge groups, nearly in constant time per operation.", ["w04-d05-shortest-paths-union-find"], [], "Path compression plus union by rank gives amortized inverse-Ackermann time, effectively constant."],
  ["dijkstra", "Dijkstra's algorithm", "dsa", "A shortest-path algorithm for graphs with non-negative edge weights that always settles the closest unsettled node next.", ["w04-d05-shortest-paths-union-find"], ["heap", "bfs"]],
  ["dfs", "Depth-first search", "dsa", "Exploring a graph by going as deep as possible along each branch before backing up.", ["w04-d02-graph-traversal"], ["stack"]],
  ["greedy-algorithm", "Greedy algorithm", "dsa", "An approach that makes the locally best choice at each step; correct only when the problem has the greedy-choice property.", ["w04-d03-dynamic-programming"]],
  ["memoization", "Memoization", "dsa", "Caching a function's results by its inputs so repeated calls are answered instantly.", ["w04-d03-dynamic-programming", "w01-d02-recursion-call-stack"], ["dynamic-programming"]],
  ["amortized-analysis", "Amortized analysis", "dsa", "Averaging the cost of operations over a long sequence, so an occasional expensive step (like resizing an array) still averages O(1).", ["w01-d02-big-o-complexity"], ["big-o"]],
  ["stable-sort", "Stable sort", "dsa", "A sort that keeps equal items in their original order, which lets you sort by several keys in turn.", ["w03-d04-sorting-algorithms"]],

  // SQL and data modeling
  ["foreign-key", "Foreign key", "sql", "A column that references a primary key in another table, enforcing that the referenced row exists.", ["w02-d01-joins-and-keys"], ["primary-key"]],
  ["inner-join", "Inner join", "sql", "A join that keeps only rows with a match on both sides.", ["w02-d01-joins-and-keys"], ["primary-key"]],
  ["anti-join", "Anti-join", "sql", "Rows in one table with no match in another, written with NOT EXISTS or a LEFT JOIN and an IS NULL filter.", ["w02-d01-joins-and-keys"], ["left-join"]],
  ["self-join", "Self-join", "sql", "Joining a table to itself, for example to pair rows from the same country or find a row's previous version.", ["w02-d01-joins-and-keys"], ["inner-join"]],
  ["group-by", "GROUP BY", "sql", "Collapsing rows that share values into one row per group so aggregates like SUM and COUNT can be computed.", ["w02-d01-sql-query-order"]],
  ["having", "HAVING", "sql", "A filter on groups that runs after GROUP BY, for conditions on aggregates such as COUNT(*) >= 2.", ["w02-d01-sql-query-order"], ["group-by"]],
  ["sql-logical-order", "Logical query order", "sql", "The order SQL clauses are evaluated: FROM and JOIN, WHERE, GROUP BY, HAVING, SELECT, ORDER BY, then LIMIT.", ["w02-d01-sql-query-order"], ["group-by"], "Explains why SELECT aliases are not visible in WHERE and why window functions cannot be filtered in the same SELECT."],
  ["null-logic", "NULL and three-valued logic", "sql", "NULL means unknown, so comparisons with it are neither true nor false; use IS NULL, COALESCE and careful outer-join filters.", ["w02-d01-joins-and-keys"]],
  ["coalesce", "COALESCE", "sql", "A function that returns its first non-NULL argument, often used to turn missing sums into 0.", ["w02-d01-joins-and-keys"], ["null-logic"]],
  ["rank-functions", "ROW_NUMBER, RANK and DENSE_RANK", "sql", "Window functions that number rows: ROW_NUMBER is always unique, RANK leaves gaps after ties, DENSE_RANK does not.", ["w02-d02-window-functions"], ["window-function"]],
  ["recursive-cte", "Recursive CTE", "sql", "A WITH query that refers to itself, used to walk hierarchies or generate a series such as a date spine.", ["w02-d02-window-functions"], ["cte"]],
  ["sql-index", "Index", "sql", "A separate sorted structure (usually a B-tree) that lets the database find rows by a column without scanning the whole table.", ["w02-d04-indexes-query-plans"], ["primary-key"], "Speeds reads, slows writes, and only helps when the predicate is selective and sargable."],
  ["query-plan", "Query plan", "sql", "The database's chosen strategy for running a query, shown with EXPLAIN: which indexes, join algorithms and order it uses.", ["w02-d04-indexes-query-plans"], ["sql-index"]],
  ["covering-index", "Covering index", "sql", "An index that contains every column a query needs, so the table itself is never read.", ["w02-d04-indexes-query-plans"], ["sql-index"]],
  ["acid", "ACID", "sql", "Transaction guarantees: atomicity (all or nothing), consistency (rules hold), isolation (concurrent transactions do not interfere) and durability (committed data survives crashes).", ["w02-d05-transactions-normalization"]],
  ["isolation-level", "Isolation level", "sql", "How strongly concurrent transactions are separated, from READ UNCOMMITTED through READ COMMITTED and REPEATABLE READ to SERIALIZABLE.", ["w02-d05-transactions-normalization"], ["acid"]],
  ["normalization", "Normalization", "sql", "Organizing tables so each fact is stored once, which prevents update anomalies.", ["w02-d05-transactions-normalization"], ["primary-key"]],
  ["denormalization", "Denormalization", "sql", "Deliberately duplicating data (for example in wide analytics tables) to make reads faster at the cost of harder updates.", ["w02-d05-transactions-normalization", "w02-d03-scd2-dimensions"], ["normalization"]],
  ["fact-table", "Fact table", "sql", "The central table in a star schema, with one row per event at a declared grain and numeric measures.", ["w02-d03-scd2-dimensions"], ["star-schema"]],
  ["dimension-table", "Dimension table", "sql", "A descriptive table (customer, product, date) joined to facts for filtering and grouping.", ["w02-d03-scd2-dimensions"], ["star-schema"]],
  ["surrogate-key", "Surrogate key", "sql", "A meaningless generated identifier for a dimension row, separate from the business key, so history versions can coexist.", ["w02-d03-scd2-dimensions"], ["scd2"]],
  ["grain", "Grain", "sql", "Exactly what one row of a table represents, such as one order line per day. Stating it prevents double counting.", ["w02-d03-scd2-dimensions", "w02-d01-joins-and-keys"]],
  ["materialized-view", "Materialized view", "sql", "A stored query result that is refreshed on a schedule or incrementally, trading freshness for fast reads.", ["w11-d01-warehouse-lakehouse"]],

  // Statistics
  ["standard-error", "Standard error", "statistics", "The standard deviation of an estimate across repeated samples; for a mean it is the data's standard deviation divided by the square root of n.", ["w05-d01-descriptive-stats-clt"], ["normal-distribution"]],
  ["clt", "Central limit theorem", "statistics", "Averages of many independent draws are approximately normally distributed, whatever the shape of the data, as long as the variance is finite.", ["w05-d01-descriptive-stats-clt"], ["normal-distribution"]],
  ["bootstrap", "Bootstrap", "statistics", "Estimating uncertainty by resampling the data with replacement many times and recomputing the statistic.", ["w05-d02-confidence-intervals-bootstrap", "w13-d05-llm-evaluation"], ["confidence-interval"]],
  ["type-i-error", "Type I error", "statistics", "A false positive: rejecting the null hypothesis when it is true. Its rate is controlled by alpha.", ["w05-d02-hypothesis-testing"], ["p-value"]],
  ["type-ii-error", "Type II error", "statistics", "A false negative: missing a real effect. Its rate is 1 minus power.", ["w05-d03-ab-test-power"], ["statistical-power"]],
  ["multiple-comparisons", "Multiple comparisons", "statistics", "Running many tests raises the chance that some look significant by luck alone.", ["w05-d03-multiple-testing"], ["p-value"], "Bonferroni and Holm control the family-wise error rate; Benjamini-Hochberg controls the false discovery rate."],
  ["false-discovery-rate", "False discovery rate", "statistics", "The expected share of 'significant' findings that are actually false positives.", ["w05-d03-multiple-testing"], ["multiple-comparisons"]],
  ["effect-size", "Effect size", "statistics", "How big a difference is, in natural units or standardized units, separate from whether it is statistically significant.", ["w05-d03-ab-test-power"], ["p-value"]],
  ["bayes-theorem", "Bayes' theorem", "statistics", "P(A given B) = P(B given A) × P(A) / P(B): how to update a belief in A after seeing evidence B.", ["w05-d04-bayesian-ab", "w08-d01-knn-naive-bayes"]],
  ["credible-interval", "Credible interval", "statistics", "A Bayesian range that contains the parameter with a stated posterior probability.", ["w05-d04-bayesian-ab"], ["posterior"]],
  ["binomial-distribution", "Binomial distribution", "statistics", "The number of successes in n independent yes/no trials with the same success probability.", ["w05-d01-probability-distributions"]],
  ["poisson-distribution", "Poisson distribution", "statistics", "The count of events in a fixed interval when they happen independently at a constant average rate.", ["w05-d01-probability-distributions"]],
  ["cuped", "CUPED", "statistics", "A variance-reduction method for A/B tests that adjusts each user's metric using their pre-experiment value, shrinking confidence intervals.", ["w05-d03-ab-test-power"], ["statistical-power"]],

  // Analytics
  ["kpi", "KPI", "analytics", "A key performance indicator: a metric a team commits to moving and reviews regularly.", ["w06-d02-metrics-funnels"]],
  ["north-star-metric", "North star metric", "analytics", "The single metric that best captures the value users get from a product, used to align teams.", ["w06-d02-kpi-root-cause", "w16-d02-product-case-interviews"], ["kpi"]],
  ["guardrail-metric", "Guardrail metric", "analytics", "A metric that must not get worse when optimizing another, such as latency or cancellations during a conversion test.", ["w16-d02-product-case-interviews", "w05-d03-ab-test-power"], ["kpi"]],
  ["retention", "Retention", "analytics", "The share of users who come back in a later period after starting.", ["w06-d03-cohort-retention"], ["cohort"]],
  ["churn", "Churn", "analytics", "Customers who stop using or paying for a product in a period; often the complement of retention.", ["w06-d03-cohort-retention", "w08-d04-kaplan-meier-survival"], ["retention"]],
  ["rfm", "RFM segmentation", "analytics", "Scoring customers on recency, frequency and monetary value to group them for targeting.", ["w06-d03-segmentation-rfm"]],
  ["metric-tree", "Metric tree", "analytics", "Breaking a top metric into multiplied or added drivers (users × conversion × order value) to locate what moved.", ["w06-d02-kpi-root-cause"], ["kpi"]],
  ["mix-shift", "Mix shift", "analytics", "A change in an overall rate caused by a change in segment proportions rather than in any segment's own rate.", ["w06-d02-kpi-root-cause"], ["simpsons-paradox"]],
  ["lie-factor", "Lie factor", "analytics", "The size of an effect shown in a chart divided by the size of the effect in the data; truncated axes inflate it.", ["w06-d04-visualization-storytelling"]],
  ["outlier", "Outlier", "analytics", "A value far from the rest of the data, from an error or a genuine extreme; investigate before removing it.", ["w06-d01-data-quality-eda"], ["iqr"]],

  // Machine learning
  ["train-validation-test", "Train, validation and test sets", "ml", "Separate data for fitting the model, choosing settings, and a final honest estimate of performance.", ["w07-d01-splits-and-leakage"]],
  ["cross-validation", "Cross-validation", "ml", "Rotating which part of the training data is held out, then averaging the scores, to estimate performance more reliably.", ["w07-d03-cross-validation-tuning"], ["train-validation-test"]],
  ["overfitting", "Overfitting", "ml", "A model that memorizes noise in the training data, scoring well there but poorly on new data.", ["w07-d02-bias-variance-regularization"]],
  ["bias-variance", "Bias-variance trade-off", "ml", "Simple models miss patterns (bias); flexible models chase noise (variance). The best model balances the two.", ["w07-d02-bias-variance-regularization"], ["overfitting"]],
  ["regularization", "Regularization", "ml", "Penalizing model complexity, for example large coefficients, to reduce overfitting.", ["w07-d02-bias-variance-regularization"], ["overfitting"], "L2 (ridge) shrinks coefficients smoothly; L1 (lasso) can set some exactly to zero."],
  ["one-hot-encoding", "One-hot encoding", "ml", "Turning a category into a set of 0/1 columns, one per category value.", ["w07-d01-feature-engineering"]],
  ["target-encoding", "Target encoding", "ml", "Replacing a category with a (smoothed) average of the target for that category, computed out of fold to avoid leakage.", ["w07-d01-feature-engineering"], ["data-leakage"]],
  ["class-imbalance", "Class imbalance", "ml", "When one class is much rarer than the other, making accuracy misleading and threshold choice important.", ["w07-d05-imbalanced-data"], ["precision-recall"]],
  ["confusion-matrix", "Confusion matrix", "ml", "A table of true positives, false positives, false negatives and true negatives at a chosen threshold.", ["w07-d03-classification-metrics"]],
  ["f1-score", "F1 score", "ml", "The harmonic mean of precision and recall.", ["w07-d03-classification-metrics"], ["precision-recall"]],
  ["log-loss", "Log loss", "ml", "The average negative log probability assigned to the true labels; punishes confident wrong predictions heavily.", ["w07-d03-classification-metrics"], ["calibration"]],
  ["decision-tree", "Decision tree", "ml", "A model that splits data with yes/no questions on features until the leaves are nearly pure.", ["w07-d04-trees-boosting"]],
  ["gini-impurity", "Gini impurity", "ml", "A measure of how mixed the labels in a node are: 0 when pure, larger when classes are mixed.", ["w07-d04-trees-boosting"], ["decision-tree"]],
  ["random-forest", "Random forest", "ml", "An average of many decision trees, each trained on a bootstrap sample with random feature subsets.", ["w07-d04-trees-boosting"], ["decision-tree", "bootstrap"]],

  // Advanced ML
  ["knn", "k-nearest neighbors", "advanced-ml", "Predicting from the k most similar training examples, by vote or average.", ["w08-d01-knn-naive-bayes"], [], "Needs scaled features and suffers in high dimensions; at scale it becomes approximate nearest neighbor search."],
  ["naive-bayes", "Naive Bayes", "advanced-ml", "A classifier that applies Bayes' theorem assuming features are independent given the class; fast and strong on text.", ["w08-d01-knn-naive-bayes"], ["bayes-theorem"]],
  ["collaborative-filtering", "Collaborative filtering", "advanced-ml", "Recommending from patterns in user-item interactions, such as 'people who liked this also liked that'.", ["w08-d02-recommender-systems"]],
  ["cold-start", "Cold start", "advanced-ml", "The difficulty of recommending for new users or new items that have no interaction history.", ["w08-d02-recommender-systems"], ["collaborative-filtering"]],
  ["shap", "SHAP values", "advanced-ml", "Per-feature contributions to one prediction, based on Shapley values, that add up to the prediction minus the average prediction.", ["w08-d04-model-interpretability"]],
  ["permutation-importance", "Permutation importance", "advanced-ml", "How much a model's score drops when one feature's values are shuffled, breaking its link to the target.", ["w08-d04-model-interpretability"]],
  ["survival-analysis", "Survival analysis", "advanced-ml", "Modeling time until an event (churn, failure) while handling subjects whose event has not happened yet.", ["w08-d04-kaplan-meier-survival"], ["censoring"]],
  ["exponential-smoothing", "Exponential smoothing", "advanced-ml", "A forecast that weights recent observations more, with weights decaying geometrically into the past.", ["w08-d02-anomaly-forecasting"]],
  ["propensity-score", "Propensity score", "advanced-ml", "The probability of receiving a treatment given observed features, used to match or weight groups in observational studies.", ["w08-d03-causal-inference"], ["confounder"]],

  // Deep learning
  ["activation-function", "Activation function", "deep-learning", "The nonlinear function applied after each layer (ReLU, GELU, tanh) that lets networks model curved relationships.", ["w09-d01-backpropagation"]],
  ["softmax", "Softmax", "deep-learning", "Turning a list of scores into probabilities that are positive and sum to 1.", ["w09-d03-attention-transformers", "w13-d03-decoding-structured-output"]],
  ["cross-entropy", "Cross-entropy loss", "deep-learning", "The standard classification loss: the negative log probability the model gave the correct class.", ["w09-d01-backpropagation"], ["softmax"]],
  ["adam", "Adam optimizer", "deep-learning", "A gradient optimizer that keeps running averages of gradients and squared gradients to give each parameter its own step size.", ["w09-d02-optimizers-regularization"], ["learning-rate"]],
  ["dropout", "Dropout", "deep-learning", "Randomly zeroing units during training so the network cannot rely on any single one; switched off at inference.", ["w09-d02-optimizers-regularization"], ["regularization"]],
  ["layer-normalization", "Layer normalization", "deep-learning", "Rescaling each example's activations to zero mean and unit variance within a layer; standard in transformers (often as RMSNorm).", ["w09-d03-attention-transformers"]],
  ["residual-connection", "Residual connection", "deep-learning", "Adding a layer's input to its output, giving gradients a shortcut and making very deep networks trainable.", ["w09-d03-attention-transformers", "w09-d04-cnn-rnn"]],
  ["convolution", "Convolution", "deep-learning", "Sliding a small learned filter across an input to detect local patterns, sharing weights across positions.", ["w09-d04-cnn-rnn"]],
  ["vanishing-gradient", "Vanishing gradient", "deep-learning", "Gradients shrinking as they flow back through many layers or time steps, so early layers barely learn.", ["w09-d04-cnn-rnn", "w09-d01-backpropagation"], ["backpropagation"]],
  ["mixed-precision", "Mixed precision", "deep-learning", "Training with 16-bit numbers (bf16 or fp16) for speed and memory while keeping sensitive values in fp32.", ["w09-d05-training-at-scale"]],
  ["gradient-accumulation", "Gradient accumulation", "deep-learning", "Summing gradients over several small batches before one optimizer step to simulate a larger batch.", ["w09-d05-training-at-scale"], ["backpropagation"]],
  ["data-parallelism", "Data parallelism", "deep-learning", "Training copies of a model on different slices of each batch and averaging their gradients with an all-reduce.", ["w09-d05-training-at-scale"]],
  ["zero-fsdp", "ZeRO and FSDP", "deep-learning", "Sharding optimizer states, gradients and weights across devices so each holds only a slice of the model's training memory.", ["w09-d05-training-at-scale"], ["data-parallelism"]],

  // System design
  ["latency-percentile", "Latency percentile", "system-design", "The response time below which a given share of requests fall; p99 is the time 99% of requests beat.", ["w10-d01-estimation-api-design", "w12-d01-cicd-canary"], [], "Tail latency compounds when one request fans out to many services."],
  ["throughput", "Throughput", "system-design", "How much work a system completes per unit of time, such as requests per second.", ["w10-d01-estimation-api-design"], ["qps"]],
  ["load-balancer", "Load balancer", "system-design", "A component that spreads incoming requests across servers and stops sending to unhealthy ones.", ["w10-d02-caching-load-balancing"]],
  ["cache-aside", "Cache-aside", "system-design", "Reading from a cache first and, on a miss, loading from the database and filling the cache.", ["w10-d02-caching-load-balancing"], [], "Pair it with TTLs and invalidation on writes; watch for thundering herds on popular keys."],
  ["cdn", "CDN", "system-design", "A content delivery network that caches static content in servers close to users.", ["w10-d02-caching-load-balancing"], ["cache-aside"]],
  ["sharding", "Sharding", "system-design", "Splitting data across machines by a key so each machine holds and serves part of it.", ["w10-d02-caching-load-balancing", "w10-d03-replication-queues"], ["consistent-hashing"]],
  ["replication", "Replication", "system-design", "Keeping copies of data on several machines for availability and read scaling.", ["w10-d03-replication-queues", "w10-d03-consistency-quorums"]],
  ["eventual-consistency", "Eventual consistency", "system-design", "A guarantee that replicas converge to the same value if writes stop, without promising every read is fresh.", ["w10-d03-consistency-quorums"], ["replication"]],
  ["cap-theorem", "CAP theorem", "system-design", "During a network partition, a distributed store must choose between consistency and availability.", ["w10-d03-consistency-quorums"], ["replication"]],
  ["token-bucket", "Token bucket", "system-design", "A rate limiter that refills tokens at a steady rate up to a cap; each request spends a token, allowing short bursts.", ["w10-d02-rate-limiting"]],
  ["message-queue", "Message queue", "system-design", "A buffer that decouples producers from consumers, smoothing bursts and enabling retries.", ["w10-d03-replication-queues"], [], "Most queues deliver at least once, so consumers must be idempotent."],
  ["backpressure", "Backpressure", "system-design", "Slowing or rejecting producers when consumers cannot keep up, instead of letting queues grow without bound.", ["w10-d03-replication-queues", "w10-d02-rate-limiting"], ["message-queue"]],
  ["circuit-breaker", "Circuit breaker", "system-design", "A guard that stops calling a failing dependency for a while so failures do not cascade.", ["w10-d02-rate-limiting"]],
  ["lsm-tree", "LSM tree", "system-design", "A write-optimized storage engine that buffers writes in memory and flushes sorted files that are merged in the background.", ["w10-d04-storage-engines"]],
  ["bloom-filter", "Bloom filter", "system-design", "A compact bit array that answers 'definitely not present' or 'maybe present', with no false negatives.", ["w10-d04-storage-engines"], ["hash-map"]],
  ["b-tree", "B-tree", "system-design", "A balanced, page-oriented search tree used by most relational database indexes.", ["w10-d04-storage-engines", "w02-d04-indexes-query-plans"], ["bst"]],

  // Data engineering
  ["etl-elt", "ETL and ELT", "data-engineering", "Extract, transform, load versus extract, load, transform: whether data is cleaned before or after it lands in the warehouse.", ["w11-d01-etl-elt-cdc"]],
  ["columnar-format", "Columnar format", "data-engineering", "Storing each column's values together (Parquet, ORC) so analytical queries read only the columns they need.", ["w11-d02-formats-spark-shuffle", "w11-d01-warehouse-lakehouse"]],
  ["partition-pruning", "Partition pruning", "data-engineering", "Skipping whole partitions of a table that a query's filters rule out.", ["w11-d01-warehouse-lakehouse"], ["columnar-format"]],
  ["lakehouse", "Lakehouse", "data-engineering", "Open files in object storage plus a table format (Iceberg, Delta Lake, Hudi) that adds transactions and metadata.", ["w11-d01-warehouse-lakehouse"], ["columnar-format"]],
  ["small-files-problem", "Small files problem", "data-engineering", "Too many tiny files that slow query planning and reading; fixed by compaction and better partitioning.", ["w11-d01-warehouse-lakehouse"], ["partition-pruning"]],
  ["orchestration", "Orchestration", "data-engineering", "Scheduling and running pipeline tasks as a dependency graph with retries and alerts (Airflow, Dagster, Prefect).", ["w11-d04-data-quality-orchestration"], ["topological-sort"]],
  ["exactly-once", "Exactly-once processing", "data-engineering", "Each event affects the output once despite retries, achieved with idempotent or transactional sinks and checkpoints.", ["w11-d03-streaming-windows", "w11-d01-etl-elt-cdc"], ["idempotency"]],
  ["schema-evolution", "Schema evolution", "data-engineering", "Changing a table's columns over time without breaking readers, under rules such as only adding optional fields.", ["w11-d04-data-quality-orchestration"], ["data-contract"]],

  // Cloud
  ["region-az", "Region and availability zone", "cloud", "A region is a geographic area; availability zones are isolated data centers within it. Spreading across zones survives a zone failure.", ["w12-d01-cloud-fundamentals"]],
  ["shared-responsibility", "Shared responsibility model", "cloud", "The provider secures the underlying cloud; the customer secures what they configure and put in it.", ["w12-d01-cloud-fundamentals"]],
  ["iaas-paas-saas", "IaaS, PaaS and SaaS", "cloud", "Renting raw infrastructure, a managed platform to run your code, or finished software, with less to manage at each step.", ["w12-d01-cloud-fundamentals"]],
  ["sla-slo", "SLA, SLO and SLI", "cloud", "An SLI measures service health, an SLO is the internal target for it, and an SLA is the contractual promise with penalties.", ["w12-d01-cloud-fundamentals"], ["latency-percentile"]],
  ["spot-instance", "Spot or preemptible instance", "cloud", "Spare cloud capacity sold at a discount that the provider can reclaim at short notice.", ["w12-d01-cloud-fundamentals"]],
  ["vpc", "VPC", "cloud", "A virtual private cloud: an isolated network in the cloud with its own address range, subnets and routing.", ["w12-d03-cloud-networking-iam"]],
  ["cidr", "CIDR block", "cloud", "An IP range written as address/prefix, such as 10.0.0.0/16; the prefix says how many leading bits are fixed.", ["w12-d03-cloud-networking-iam"], ["vpc"]],
  ["iam-role", "IAM role", "cloud", "An identity with permissions that people or workloads assume temporarily, instead of using long-lived keys.", ["w12-d03-cloud-networking-iam"]],
  ["least-privilege", "Least privilege", "cloud", "Granting only the permissions a person or service needs for its task, and no more.", ["w12-d03-cloud-networking-iam"], ["iam-role"]],
  ["object-storage", "Object storage", "cloud", "Storing files as objects in buckets addressed by key (Amazon S3, Google Cloud Storage, Azure Blob Storage), cheap and durable at scale.", ["w12-d03-cloud-networking-iam", "w11-d01-warehouse-lakehouse"]],
  ["container", "Container", "cloud", "A packaged application with its dependencies that runs isolated on a shared operating system kernel.", ["w12-d02-containers-kubernetes"]],
  ["kubernetes", "Kubernetes", "cloud", "An orchestrator that runs containers across a cluster, schedules them by resource requests, restarts failures and scales replicas.", ["w12-d02-containers-kubernetes"], ["container"]],
  ["autoscaling", "Autoscaling", "cloud", "Automatically adding or removing capacity based on load, for example the Kubernetes Horizontal Pod Autoscaler.", ["w12-d02-containers-kubernetes"], ["kubernetes"]],
  ["serverless", "Serverless", "cloud", "Running code or containers without managing servers, billed per request or per second, often scaling to zero.", ["w12-d02-containers-kubernetes"]],
  ["iac", "Infrastructure as code", "cloud", "Declaring cloud resources in version-controlled files (Terraform, OpenTofu, Pulumi) and applying reviewed plans.", ["w12-d04-iac-cost"]],
  ["config-drift", "Configuration drift", "cloud", "Differences between real infrastructure and its declared code, usually from manual changes.", ["w12-d04-iac-cost"], ["iac"]],

  // MLOps
  ["model-registry", "Model registry", "mlops", "A versioned store of trained models with metadata, stage (staging, production) and lineage.", ["w12-d01-cicd-canary"]],
  ["shadow-deployment", "Shadow deployment", "mlops", "Running a new model on live traffic without using its answers, to compare it safely with the current model.", ["w12-d01-cicd-canary"], ["canary-release"]],
  ["data-drift", "Data drift", "mlops", "A change in the distribution of model inputs compared with training data.", ["w12-d03-drift-observability"], ["psi"]],
  ["concept-drift", "Concept drift", "mlops", "A change in the relationship between inputs and the target, so the same inputs now mean something different.", ["w12-d03-drift-observability"], ["data-drift"]],
  ["training-serving-skew", "Training-serving skew", "mlops", "Features computed differently in training and production, so the model sees different data than it learned from.", ["w12-d02-feature-stores-serving"], ["feature-store"]],

  // LLMs
  ["tokenizer", "Tokenizer", "llm", "The component that splits text into tokens and maps them to ids, for example with byte-pair encoding (BPE).", ["w13-d01-tokenization-embeddings"], ["token"]],
  ["context-window", "Context window", "llm", "The maximum number of tokens a model can read and write in one request, prompt and output together.", ["w13-d01-tokenization-embeddings", "w13-d04-inference-kv-cache"], ["token"]],
  ["few-shot-prompting", "Few-shot prompting", "llm", "Including a handful of solved examples in the prompt to show the model the task and format.", ["w13-d01-prompt-engineering"]],
  ["structured-output", "Structured output", "llm", "Constraining or validating a model's response to a schema such as JSON so code can rely on it.", ["w13-d03-decoding-structured-output"]],
  ["hallucination", "Hallucination", "llm", "A fluent but unsupported or false statement generated by a model.", ["w14-d03-rag-evaluation", "w13-d05-llm-evaluation"], ["groundedness"]],
  ["sft", "Supervised fine-tuning", "llm", "Training a pretrained model on example prompts and ideal responses so it follows instructions.", ["w13-d02-finetuning-lora"]],
  ["rlhf", "RLHF", "llm", "Reinforcement learning from human feedback: train a reward model on human preferences, then optimize the model against it with a KL penalty.", ["w13-d02-preference-tuning-dpo"], ["sft"]],
  ["dpo", "Direct Preference Optimization", "llm", "Training directly on preferred versus rejected responses with a logistic loss on log-probability ratios, without a separate reward model.", ["w13-d02-preference-tuning-dpo"], ["rlhf"]],
  ["quantization", "Quantization", "llm", "Storing weights (and sometimes activations) with fewer bits, such as 8 or 4, to cut memory and speed up inference.", ["w13-d02-finetuning-lora", "w13-d04-inference-kv-cache"]],
  ["gqa", "Grouped-query attention", "llm", "Sharing each key-value head across several query heads, which shrinks the KV cache.", ["w13-d04-inference-kv-cache"], ["kv-cache", "attention"]],
  ["llm-as-judge", "LLM as a judge", "llm", "Using a model with a rubric to grade outputs, after checking its agreement with human labels.", ["w13-d05-llm-evaluation"]],
  ["exact-match-f1", "Exact match and token F1", "llm", "Answer metrics: exact match after normalization, and F1 over shared words for partial credit.", ["w13-d05-llm-evaluation"]],

  // RAG
  ["vector-database", "Vector database", "rag", "A store that indexes embeddings for fast similarity search, usually with metadata filtering.", ["w14-d02-vector-search-ann"], ["embedding"]],
  ["ann-search", "Approximate nearest neighbor search", "rag", "Finding vectors close to a query without comparing against every vector, trading a little recall for speed.", ["w14-d02-vector-search-ann"], ["vector-database"]],
  ["hnsw", "HNSW", "rag", "Hierarchical navigable small world graphs: an ANN index that greedily walks layered neighbor graphs.", ["w14-d02-vector-search-ann"], ["ann-search"]],
  ["ivf", "IVF index", "rag", "An inverted-file ANN index that clusters vectors and searches only the closest clusters (nprobe of them).", ["w14-d02-vector-search-ann"], ["ann-search", "k-means"]],
  ["cosine-similarity", "Cosine similarity", "rag", "The cosine of the angle between two vectors: 1 when they point the same way, 0 when unrelated.", ["w13-d01-tokenization-embeddings", "w14-d02-vector-search-ann"], ["embedding"]],
  ["rrf", "Reciprocal rank fusion", "rag", "Combining rankings by summing 1 / (k + rank) across lists, used to merge keyword and vector results.", ["w14-d02-bm25-hybrid-retrieval"], ["hybrid-search"]],
  ["retrieval-metrics", "Recall@k, MRR and nDCG", "rag", "Retrieval quality measures: how many relevant items appear in the top k, how early the first one appears, and how well items are ordered.", ["w14-d03-rag-evaluation"]],
  ["metadata-filtering", "Metadata filtering", "rag", "Restricting retrieval to documents with matching attributes (tenant, date, version) before or during vector search.", ["w14-d01-chunking-ingestion", "w14-d02-vector-search-ann"], ["vector-database"]],

  // Agents
  ["react-pattern", "ReAct pattern", "agents", "An agent loop that alternates reasoning about what to do with acting through tools and reading the results.", ["w15-d02-tools-planning-memory"], ["tool-call"]],
  ["agent-memory", "Agent memory", "agents", "State an agent keeps across steps or sessions, from the running scratchpad to stored facts retrieved later.", ["w15-d02-tools-planning-memory"], ["agent"]],
  ["guardrail", "Guardrail", "agents", "A check outside the model that blocks or modifies unsafe inputs, outputs or actions.", ["w15-d03-guardrails-budgets-tracing"], ["agent"]],
  ["tracing", "Tracing", "agents", "Recording each step of a request (model calls, tool calls, tokens, latency) as linked spans for debugging and evaluation.", ["w15-d03-guardrails-budgets-tracing"]],
  ["pass-at-k", "pass@k and pass^k", "agents", "pass@k: at least one of k attempts succeeds (capability). pass^k: all k attempts succeed (reliability).", ["w15-d04-agent-evaluation"], ["agent"]],
  ["mcp", "Model Context Protocol", "agents", "An open protocol for connecting AI applications to tools and data sources through a standard client-server interface.", ["w15-d02-tools-planning-memory"], ["tool-call"]],

  // Interviews
  ["fermi-estimate", "Fermi estimate", "career", "A quick order-of-magnitude estimate built by multiplying stated assumptions, with a range rather than one number.", ["w16-d02-product-case-interviews", "w10-d01-estimation-api-design"]],
  ["capstone", "Capstone project", "career", "An end-to-end project that shows scoping, a baseline, evaluation and trade-offs on a realistic problem.", ["w16-d01-capstone-scoping"]],
];

export const glossaryExtra: GlossaryTermInput[] = TERMS.map(term);
