import type { PracticeSetInput } from "@/lib/content-types";

/** Shared SQLite schema and data for every SQL drill. Small enough to reason about by hand. */
export const SQL_SETUP = `CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT NOT NULL, country TEXT NOT NULL, signup_date TEXT NOT NULL);
CREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL, order_date TEXT NOT NULL, amount REAL NOT NULL, category TEXT NOT NULL);
CREATE TABLE promotions (order_id INTEGER NOT NULL, code TEXT NOT NULL);
CREATE TABLE events (user_id INTEGER NOT NULL, event TEXT NOT NULL, ts TEXT NOT NULL);
INSERT INTO customers VALUES (1, 'Ada', 'US', '2026-01-01'), (2, 'Grace', 'UK', '2026-01-03'), (3, 'Linus', 'FI', '2026-01-08'), (4, 'Margaret', 'US', '2026-01-10'), (5, 'Alan', 'UK', '2026-01-12');
INSERT INTO orders VALUES (101, 1, '2026-01-02', 30.0, 'books'), (102, 1, '2026-01-05', 20.0, 'games'), (103, 2, '2026-01-05', 99.0, 'electronics'), (104, 3, '2026-01-09', 15.0, 'books'), (105, 3, '2026-01-15', 45.0, 'books'), (106, 1, '2026-01-20', 50.0, 'electronics'), (107, 2, '2026-01-21', 99.0, 'games'), (108, 4, '2026-01-22', 12.5, 'books');
INSERT INTO promotions VALUES (101, 'NEWYEAR'), (101, 'BOOKS10'), (103, 'TECH5'), (106, 'TECH5');
INSERT INTO events VALUES (1, 'visit', '2026-01-01 09:00'), (1, 'signup', '2026-01-01 09:05'), (1, 'purchase', '2026-01-02 10:00'), (2, 'visit', '2026-01-03 12:00'), (2, 'signup', '2026-01-03 12:30'), (3, 'signup', '2026-01-08 08:00'), (3, 'visit', '2026-01-08 08:10'), (4, 'visit', '2026-01-10 18:00'), (5, 'visit', '2026-01-12 07:00'), (5, 'signup', '2026-01-12 07:20'), (5, 'purchase', '2026-01-13 07:00');`;

export const practiceSets: PracticeSetInput[] = [
  {
    id: "sql",
    title: "SQL drills",
    description:
      "Write queries against a small store database (customers, orders, promotions, events). Your query runs in SQLite in your browser and is compared with the expected result.",
    items: [
      {
        kind: "sql",
        id: "sql-left-join-totals",
        title: "Revenue per customer, including customers with no orders",
        prompt: "Return name, orders (count) and revenue (sum, 0 when none) for every customer, highest revenue first, then by name.",
        topicIds: ["w02-d01-joins-and-keys"],
        difficulty: "beginner",
        hints: ["Which join keeps customers without orders?", "COUNT(o.id) skips NULLs; COUNT(*) does not."],
        setup: SQL_SETUP,
        solution: `SELECT c.name, COUNT(o.id) AS orders, COALESCE(SUM(o.amount), 0) AS revenue
FROM customers c LEFT JOIN orders o ON o.customer_id = c.id
GROUP BY c.id, c.name ORDER BY revenue DESC, c.name`,
        expectedColumns: ["name", "orders", "revenue"],
        expectedRows: [["Grace", 2, 198], ["Ada", 3, 100], ["Linus", 2, 60], ["Margaret", 1, 12.5], ["Alan", 0, 0]],
        orderMatters: true,
      },
      {
        kind: "sql",
        id: "sql-anti-join",
        title: "Customers who never ordered",
        prompt: "Return the name of every customer with no orders, sorted by name.",
        topicIds: ["w02-d01-joins-and-keys"],
        difficulty: "beginner",
        hints: ["Use NOT EXISTS or a LEFT JOIN with an IS NULL filter on the right table's key."],
        setup: SQL_SETUP,
        solution: `SELECT c.name FROM customers c
WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id) ORDER BY c.name`,
        expectedColumns: ["name"],
        expectedRows: [["Alan"]],
        orderMatters: true,
      },
      {
        kind: "sql",
        id: "sql-top-order-per-customer",
        title: "Largest order per customer, keeping ties",
        prompt: "For each customer with orders, return name, order_id and amount of their largest order. If two orders tie, return both. Sort by name, then order_id.",
        topicIds: ["w02-d02-window-functions"],
        difficulty: "intermediate",
        hints: ["RANK keeps ties; ROW_NUMBER does not.", "Filter on the rank outside the window query."],
        setup: SQL_SETUP,
        solution: `WITH ranked AS (
  SELECT c.name, o.id AS order_id, o.amount,
         RANK() OVER (PARTITION BY o.customer_id ORDER BY o.amount DESC) AS rnk
  FROM orders o JOIN customers c ON c.id = o.customer_id)
SELECT name, order_id, amount FROM ranked WHERE rnk = 1 ORDER BY name, order_id`,
        expectedColumns: ["name", "order_id", "amount"],
        expectedRows: [["Ada", 106, 50], ["Grace", 103, 99], ["Grace", 107, 99], ["Linus", 105, 45], ["Margaret", 108, 12.5]],
        orderMatters: true,
      },
      {
        kind: "sql",
        id: "sql-running-revenue",
        title: "Daily revenue with a running total",
        prompt: "Return order_date, revenue for that day, and running_revenue up to and including that day, sorted by date.",
        topicIds: ["w02-d02-window-functions"],
        difficulty: "intermediate",
        hints: ["Aggregate by day first, then apply SUM(...) OVER (ORDER BY order_date) to the daily sums."],
        setup: SQL_SETUP,
        solution: `SELECT order_date, SUM(amount) AS revenue,
       SUM(SUM(amount)) OVER (ORDER BY order_date) AS running_revenue
FROM orders GROUP BY order_date ORDER BY order_date`,
        expectedColumns: ["order_date", "revenue", "running_revenue"],
        expectedRows: [
          ["2026-01-02", 30, 30],
          ["2026-01-05", 119, 149],
          ["2026-01-09", 15, 164],
          ["2026-01-15", 45, 209],
          ["2026-01-20", 50, 259],
          ["2026-01-21", 99, 358],
          ["2026-01-22", 12.5, 370.5],
        ],
        orderMatters: true,
      },
      {
        kind: "sql",
        id: "sql-latest-event",
        title: "Latest event per user",
        prompt: "Return user_id, event and ts of each user's most recent event, sorted by user_id.",
        topicIds: ["w02-d02-window-functions"],
        difficulty: "intermediate",
        hints: ["ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY ts DESC) and keep row 1."],
        setup: SQL_SETUP,
        solution: `WITH ranked AS (
  SELECT user_id, event, ts, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY ts DESC) AS rn
  FROM events)
SELECT user_id, event, ts FROM ranked WHERE rn = 1 ORDER BY user_id`,
        expectedColumns: ["user_id", "event", "ts"],
        expectedRows: [
          [1, "purchase", "2026-01-02 10:00"],
          [2, "signup", "2026-01-03 12:30"],
          [3, "visit", "2026-01-08 08:10"],
          [4, "visit", "2026-01-10 18:00"],
          [5, "purchase", "2026-01-13 07:00"],
        ],
        orderMatters: true,
      },
      {
        kind: "sql",
        id: "sql-ordered-funnel",
        title: "Visit to signup, in order",
        prompt: "Return visited (distinct users with a visit) and signed_up_after_visit (distinct users whose signup is at or after one of their visits).",
        topicIds: ["w06-d02-metrics-funnels"],
        difficulty: "intermediate",
        hints: ["Join events to itself on user_id with the time condition in the ON clause.", "User 3 signed up before visiting."],
        setup: SQL_SETUP,
        solution: `SELECT COUNT(DISTINCT v.user_id) AS visited,
       COUNT(DISTINCT s.user_id) AS signed_up_after_visit
FROM events v
LEFT JOIN events s ON s.user_id = v.user_id AND s.event = 'signup' AND s.ts >= v.ts
WHERE v.event = 'visit'`,
        expectedColumns: ["visited", "signed_up_after_visit"],
        expectedRows: [[5, 3]],
        orderMatters: false,
      },
      {
        kind: "sql",
        id: "sql-two-week-conversion",
        title: "Customers who ordered within 14 days of signup",
        prompt: "Return pct_ordered_within_14_days: the percentage of all customers (rounded to 1 decimal) who placed an order 0 to 14 days after their signup date.",
        topicIds: ["w06-d03-cohort-retention", "w02-d01-joins-and-keys"],
        difficulty: "intermediate",
        hints: ["julianday(a) - julianday(b) gives days between ISO dates.", "The denominator is every customer, including those with no orders."],
        setup: SQL_SETUP,
        solution: `SELECT ROUND(100.0 * COUNT(DISTINCT o.customer_id) / (SELECT COUNT(*) FROM customers), 1) AS pct_ordered_within_14_days
FROM customers c JOIN orders o ON o.customer_id = c.id
WHERE julianday(o.order_date) - julianday(c.signup_date) BETWEEN 0 AND 14`,
        expectedColumns: ["pct_ordered_within_14_days"],
        expectedRows: [[80]],
        orderMatters: false,
      },
      {
        kind: "sql",
        id: "sql-fanout-trap",
        title: "Revenue from promoted orders without double counting",
        prompt: "Return promo_revenue: total amount of orders that used at least one promotion. Order 101 used two codes; count it once.",
        topicIds: ["w02-d01-joins-and-keys"],
        difficulty: "intermediate",
        hints: ["Joining promotions directly repeats order 101.", "Deduplicate order ids first, or use EXISTS."],
        setup: SQL_SETUP,
        solution: `WITH promo_orders AS (SELECT DISTINCT order_id FROM promotions)
SELECT ROUND(SUM(o.amount), 2) AS promo_revenue
FROM orders o JOIN promo_orders p ON p.order_id = o.id`,
        expectedColumns: ["promo_revenue"],
        expectedRows: [[179]],
        orderMatters: false,
      },
      {
        kind: "sql",
        id: "sql-category-share",
        title: "Each category's share of revenue",
        prompt: "Return category, revenue and pct_of_total (rounded to 1 decimal), highest revenue first, then by category.",
        topicIds: ["w02-d02-window-functions", "w06-d02-metrics-funnels"],
        difficulty: "intermediate",
        hints: ["SUM(SUM(amount)) OVER () gives the grand total next to each group."],
        setup: SQL_SETUP,
        solution: `SELECT category, SUM(amount) AS revenue,
       ROUND(100.0 * SUM(amount) / SUM(SUM(amount)) OVER (), 1) AS pct_of_total
FROM orders GROUP BY category ORDER BY revenue DESC, category`,
        expectedColumns: ["category", "revenue", "pct_of_total"],
        expectedRows: [["electronics", 149, 40.2], ["games", 119, 32.1], ["books", 102.5, 27.7]],
        orderMatters: true,
      },
      {
        kind: "sql",
        id: "sql-days-between-orders",
        title: "Days since each customer's previous order",
        prompt: "Return name, order_id and days_since_previous (an integer, NULL for a customer's first order), sorted by name, order date, then order id.",
        topicIds: ["w02-d02-window-functions"],
        difficulty: "advanced",
        hints: ["LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date)", "Cast the julianday difference to INTEGER."],
        setup: SQL_SETUP,
        solution: `SELECT c.name, o.id AS order_id,
       CAST(julianday(o.order_date) - julianday(LAG(o.order_date) OVER (PARTITION BY o.customer_id ORDER BY o.order_date, o.id)) AS INTEGER) AS days_since_previous
FROM orders o JOIN customers c ON c.id = o.customer_id
ORDER BY c.name, o.order_date, o.id`,
        expectedColumns: ["name", "order_id", "days_since_previous"],
        expectedRows: [
          ["Ada", 101, null],
          ["Ada", 102, 3],
          ["Ada", 106, 15],
          ["Grace", 103, null],
          ["Grace", 107, 16],
          ["Linus", 104, null],
          ["Linus", 105, 6],
          ["Margaret", 108, null],
        ],
        orderMatters: true,
      },
    ],
  },
  {
    id: "statistics",
    title: "Statistics drills",
    description: "Numeric questions answered to a stated tolerance. Each stored answer is recomputed in CI from the verification code shown with the solution.",
    items: [
      {
        kind: "numeric",
        id: "stat-binomial-two-heads",
        title: "Exactly two heads",
        prompt: "A fair coin is flipped 5 times. What is the probability of exactly 2 heads?",
        topicIds: ["w05-d01-probability-distributions"],
        difficulty: "beginner",
        answer: 0.3125,
        tolerance: 0.0005,
        solution: "C(5, 2) x 0.5^5 = 10 / 32 = 0.3125.",
        verifyPython: "from math import comb\nprint(comb(5, 2) * 0.5**5)",
      },
      {
        kind: "numeric",
        id: "stat-normal-upper-tail",
        title: "Upper tail of the standard normal",
        prompt: "For Z ~ Normal(0, 1), what is P(Z > 1.96)?",
        topicIds: ["w05-d01-probability-distributions"],
        difficulty: "beginner",
        answer: 0.025,
        tolerance: 0.0005,
        solution: "1 - Phi(1.96) is about 0.025, which is why 1.96 is the two-sided 95% critical value.",
        verifyPython: "from statistics import NormalDist\nprint(1 - NormalDist().cdf(1.96))",
      },
      {
        kind: "numeric",
        id: "stat-sample-size-5pct",
        title: "Users per arm for a 1-point lift on 5%",
        prompt: "Baseline conversion is 5%. How many users per arm detect an absolute lift to 6% with alpha 0.05 (two-sided) and 80% power? Round up.",
        topicIds: ["w05-d03-ab-test-power"],
        difficulty: "intermediate",
        answer: 8158,
        tolerance: 1,
        unit: "users per arm",
        solution: "n = (z_0.975 sqrt(2 p_bar q_bar) + z_0.8 sqrt(p1 q1 + p2 q2))^2 / (p2 - p1)^2 with p_bar = 0.055, giving 8,158 after rounding up.",
        verifyPython:
          "from math import ceil, sqrt\nfrom statistics import NormalDist\nZ = NormalDist()\np1, p2 = 0.05, 0.06\npb = (p1 + p2) / 2\na = Z.inv_cdf(0.975) * sqrt(2 * pb * (1 - pb))\nb = Z.inv_cdf(0.8) * sqrt(p1 * (1 - p1) + p2 * (1 - p2))\nprint(ceil((a + b) ** 2 / (p2 - p1) ** 2))",
      },
      {
        kind: "numeric",
        id: "stat-two-proportion-z",
        title: "z statistic for two conversion rates",
        prompt: "Control converts 120 of 1,000 users, treatment 150 of 1,000. What is the pooled two-proportion z statistic?",
        topicIds: ["w05-d02-hypothesis-testing"],
        difficulty: "intermediate",
        answer: 1.963,
        tolerance: 0.005,
        solution: "Pooled p = 270 / 2000 = 0.135; SE = sqrt(0.135 x 0.865 x 2 / 1000) = 0.01528; z = 0.03 / 0.01528, about 1.96.",
        verifyPython: "from math import sqrt\np1, p2 = 120 / 1000, 150 / 1000\np = 270 / 2000\nprint((p2 - p1) / sqrt(p * (1 - p) * (2 / 1000)))",
      },
      {
        kind: "numeric",
        id: "stat-ci-half-width",
        title: "Margin of error for a proportion",
        prompt: "A survey of 400 people finds 30% agree. What is the half-width of the 95% Wald confidence interval?",
        topicIds: ["w05-d02-hypothesis-testing"],
        difficulty: "beginner",
        answer: 0.0449,
        tolerance: 0.0005,
        solution: "1.96 x sqrt(0.3 x 0.7 / 400) = 1.96 x 0.0229, about 0.045.",
        verifyPython: "from math import sqrt\nfrom statistics import NormalDist\nprint(NormalDist().inv_cdf(0.975) * sqrt(0.3 * 0.7 / 400))",
      },
      {
        kind: "numeric",
        id: "stat-expected-rolls",
        title: "Expected rolls until a six",
        prompt: "How many rolls of a fair die do you expect until the first 6 (including the roll that shows 6)?",
        topicIds: ["w05-d01-probability-distributions"],
        difficulty: "beginner",
        answer: 6,
        tolerance: 0.001,
        solution: "A geometric distribution with p = 1/6 has mean 1 / p = 6.",
        verifyPython: "print(1 / (1 / 6))",
      },
      {
        kind: "numeric",
        id: "stat-bayes-screening",
        title: "Positive test, actual disease",
        prompt: "A test has 99% sensitivity and 95% specificity. Prevalence is 1%. Given a positive test, what is the probability of disease?",
        topicIds: ["w05-d04-bayesian-ab"],
        difficulty: "intermediate",
        answer: 0.1667,
        tolerance: 0.0005,
        solution: "P(D|+) = 0.99 x 0.01 / (0.99 x 0.01 + 0.05 x 0.99) = 0.0099 / 0.0594, about 0.167. Base rates dominate.",
        verifyPython: "sens, spec, prev = 0.99, 0.95, 0.01\nprint(sens * prev / (sens * prev + (1 - spec) * (1 - prev)))",
      },
      {
        kind: "numeric",
        id: "stat-poisson-at-least-one",
        title: "At least one incident",
        prompt: "Incidents occur at an average rate of 0.5 per week (Poisson). What is the probability of at least one incident next week?",
        topicIds: ["w05-d01-probability-distributions"],
        difficulty: "beginner",
        answer: 0.3935,
        tolerance: 0.0005,
        solution: "1 - P(0) = 1 - e^-0.5, about 0.393.",
        verifyPython: "from math import exp\nprint(1 - exp(-0.5))",
      },
      {
        kind: "numeric",
        id: "stat-standard-error",
        title: "Standard error of a mean",
        prompt: "A sample of 36 has standard deviation 12. What is the standard error of the mean?",
        topicIds: ["w05-d02-hypothesis-testing"],
        difficulty: "beginner",
        answer: 2,
        tolerance: 0.001,
        solution: "SE = s / sqrt(n) = 12 / 6 = 2.",
        verifyPython: "from math import sqrt\nprint(12 / sqrt(36))",
      },
      {
        kind: "numeric",
        id: "stat-achieved-power",
        title: "Power of an underpowered test",
        prompt: "With 500 users per arm, what power does a two-sided test at alpha 0.05 have to detect a true change from 20% to 25%?",
        topicIds: ["w05-d03-ab-test-power"],
        difficulty: "advanced",
        answer: 0.4733,
        tolerance: 0.002,
        solution: "Using the normal approximation, power = Phi((0.05 sqrt(500) - 1.96 sqrt(2 x 0.225 x 0.775)) / sqrt(0.2 x 0.8 + 0.25 x 0.75)), about 0.47: worse than a coin flip at catching a real effect.",
        verifyPython:
          "from math import sqrt\nfrom statistics import NormalDist\nZ = NormalDist()\np1, p2, n = 0.20, 0.25, 500\npb = (p1 + p2) / 2\nnum = abs(p2 - p1) * sqrt(n) - Z.inv_cdf(0.975) * sqrt(2 * pb * (1 - pb))\nprint(Z.cdf(num / sqrt(p1 * (1 - p1) + p2 * (1 - p2))))",
      },
      {
        kind: "numeric",
        id: "stat-srm-p-value",
        title: "Sample ratio mismatch",
        prompt: "A 50/50 test assigned 50,400 users to A and 49,600 to B. What is the chi-square test p-value for a sample ratio mismatch?",
        topicIds: ["w05-d02-hypothesis-testing"],
        difficulty: "advanced",
        answer: 0.0114,
        tolerance: 0.0005,
        solution: "chi2 = 400^2 / 50000 x 2 = 6.4 with 1 degree of freedom; p = 2 (1 - Phi(sqrt(6.4))), about 0.011. That is suspicious: investigate assignment before trusting results.",
        verifyPython:
          "from math import sqrt\nfrom statistics import NormalDist\nchi2 = (50400 - 50000) ** 2 / 50000 + (49600 - 50000) ** 2 / 50000\nprint(2 * (1 - NormalDist().cdf(sqrt(chi2))))",
      },
      {
        kind: "numeric",
        id: "stat-psi-two-bins",
        title: "PSI with two bins",
        prompt: "Baseline shares are 50% and 50%; this week they are 70% and 30%. What is the population stability index?",
        topicIds: ["w12-d03-drift-observability"],
        difficulty: "intermediate",
        answer: 0.1695,
        tolerance: 0.0005,
        solution: "(0.7 - 0.5) ln(0.7 / 0.5) + (0.3 - 0.5) ln(0.3 / 0.5) = 0.0673 + 0.1022, about 0.17: moderate shift by the usual rule of thumb.",
        verifyPython: "from math import log\ne, a = [0.5, 0.5], [0.7, 0.3]\nprint(sum((ai - ei) * log(ai / ei) for ei, ai in zip(e, a)))",
      },
    ],
  },
  {
    id: "system-design",
    title: "System design prompts",
    description: "Timed design prompts. Write your design, then score yourself against the rubric and compare with the model answer.",
    items: [
      {
        kind: "design",
        id: "sd-rate-limiter",
        title: "Distributed rate limiter",
        prompt: "Design a rate limiter for a public API: 100 requests per minute per API key, 20 stateless API servers, under 2 ms added latency.",
        topicIds: ["w03-d02-sliding-window", "w10-d02-caching-load-balancing"],
        difficulty: "intermediate",
        minutes: 30,
        rubric: [
          "Compares fixed window, sliding window and token bucket algorithms",
          "Centralized counters (for example Redis with atomic scripts) with a fail-open or fail-closed decision",
          "Handles hot keys and clock issues",
          "Returns 429 with Retry-After and exposes limits in headers",
        ],
        modelAnswer:
          "Token bucket per key stored in Redis, updated atomically with a Lua script (tokens, last refill time). API servers call Redis once per request (sub-millisecond in-region). Local in-memory pre-checks for very hot keys. If Redis is unavailable, fail open for low-risk endpoints and closed for expensive ones. Return 429 with Retry-After and X-RateLimit headers. Monitor rejection rate and Redis latency.",
      },
      {
        kind: "design",
        id: "sd-notifications",
        title: "Notification service",
        prompt: "Design a service that sends email, SMS and push notifications for 50 million users, with user preferences, retries and no duplicate sends.",
        topicIds: ["w10-d03-replication-queues", "w10-d01-estimation-api-design"],
        difficulty: "intermediate",
        minutes: 35,
        rubric: [
          "Estimates volume and peak rates",
          "Queue per channel with idempotency keys to prevent duplicates",
          "Preference and quiet-hours checks before enqueueing",
          "Retries with backoff, dead-letter queues and provider failover",
          "Delivery tracking and metrics",
        ],
        modelAnswer:
          "API accepts notification requests with an idempotency key; a preference service filters by channel opt-ins and quiet hours; messages go to per-channel queues; workers call providers with exponential backoff and provider failover; a dedupe table keyed by (user, idempotency key, channel) prevents double sends; failures go to a DLQ; delivery receipts update a status store; dashboards track send latency, failure rate per provider and opt-out rates.",
      },
      {
        kind: "design",
        id: "sd-news-feed",
        title: "News feed",
        prompt: "Design a home feed for a social app with 100 million daily users where some accounts have millions of followers.",
        topicIds: ["w10-d02-caching-load-balancing", "w10-d01-estimation-api-design"],
        difficulty: "advanced",
        minutes: 40,
        rubric: [
          "Fan-out on write for normal users and fan-out on read for celebrities (hybrid)",
          "Feed cache per user with pagination by cursor",
          "Ranking stage separated from candidate retrieval",
          "Handles deletes, privacy changes and backfills",
        ],
        modelAnswer:
          "Posts are stored once; for most authors a fan-out service pushes post ids into followers' feed caches (Redis lists, capped). Celebrity posts are pulled at read time and merged. Reading the feed fetches cached ids plus celebrity candidates, ranks them with a lightweight model, then hydrates post details. Cursor pagination, tombstones for deletes, and asynchronous backfill when users follow someone new.",
      },
      {
        kind: "design",
        id: "sd-metrics-ingestion",
        title: "Metrics ingestion pipeline",
        prompt: "Design ingestion for 2 million events per second of product analytics, available in dashboards within 1 minute and in the warehouse within 1 hour.",
        topicIds: ["w11-d03-streaming-windows", "w11-d02-formats-spark-shuffle", "w11-d04-data-quality-orchestration"],
        difficulty: "advanced",
        minutes: 40,
        rubric: [
          "Partitioned log (Kafka) sized from throughput",
          "Stream processing with event-time windows and watermarks for the 1-minute path",
          "Columnar, partitioned files for the warehouse path with compaction",
          "Schema registry, data quality checks and late-data handling",
        ],
        modelAnswer:
          "Clients batch events to collectors, which write to Kafka partitioned by user id. A Flink job computes minute-level aggregates with event-time windows and a watermark, writing to a real-time store for dashboards; late events go to a side output. A separate job writes raw events as Parquet partitioned by date and hour to object storage, compacted hourly and registered in the lakehouse catalog. A schema registry enforces contracts; quality checks gate publishes.",
      },
      {
        kind: "design",
        id: "sd-feature-store",
        title: "Feature platform for real-time fraud scoring",
        prompt: "Design the feature pipeline and serving path for a fraud model that must score card transactions in 50 ms p99.",
        topicIds: ["w12-d02-feature-stores-serving", "w12-d01-cicd-canary"],
        difficulty: "advanced",
        minutes: 35,
        rubric: [
          "Streaming aggregates into an online store with low-latency reads",
          "Same feature definitions offline for point-in-time training data",
          "Latency budget broken down across network, features and model",
          "Fallback behavior and monitoring of feature freshness",
        ],
        modelAnswer:
          "Transactions stream into Flink jobs that maintain rolling counts and amounts per card and merchant, written to Redis (online) and to the offline store with event timestamps. The scoring service fetches features in one batched read (about 5 ms), runs a gradient-boosted model in-process (about 2 ms) and returns a score. Training uses point-in-time joins from the offline store. If features are stale or missing, fall back to rules and alert on freshness lag.",
      },
      {
        kind: "design",
        id: "sd-llm-gateway",
        title: "LLM gateway for an enterprise",
        prompt: "Design a shared gateway that all internal teams use to call LLM providers, with cost control, logging, safety and failover.",
        topicIds: ["w13-d04-inference-kv-cache", "w15-d03-guardrails-budgets-tracing", "w13-d03-decoding-structured-output"],
        difficulty: "advanced",
        minutes: 35,
        rubric: [
          "Unified API with per-team keys, quotas and budgets",
          "Request and response logging with PII redaction and retention rules",
          "Provider routing, retries and failover",
          "Caching, rate limits and safety filters with audit trails",
        ],
        modelAnswer:
          "A gateway service exposes one API, authenticates teams, enforces per-team rate limits and monthly budgets, and routes to providers by model, cost and health with retries and failover. Prompts and responses are logged with PII redaction and configurable retention; traces include tokens, latency and cost. Optional exact-match and prefix caching cut cost. Safety filters and policy checks run before and after calls, with audit logs and dashboards per team.",
      },
    ],
  },
  {
    id: "rag-diagnosis",
    title: "RAG diagnosis",
    description: "Each scenario describes a misbehaving RAG system. Pick the most likely root cause, then read the explanation.",
    items: [
      {
        kind: "choice",
        id: "rag-split-qualifier",
        title: "The missing exception",
        prompt: "Users ask 'Can I return a final-sale jacket?' The bot says yes. The policy says returns are allowed within 30 days, then two paragraphs later says final-sale items are excluded. Retrieval returns the first paragraph only.",
        topicIds: ["w14-d01-chunking-ingestion"],
        difficulty: "intermediate",
        options: [
          "The embedding model is too small",
          "Chunking separated the rule from its exception, so only the general rule is retrieved",
          "Temperature is too high",
          "The reranker is ordering results randomly",
        ],
        correct: 1,
        explanation: "The qualifier lives in another chunk. Chunk by section, add overlap or parent-section context, and test with exception questions.",
      },
      {
        kind: "choice",
        id: "rag-identifier-miss",
        title: "Error code not found",
        prompt: "Searching 'error E4012' returns generic troubleshooting pages, although one page is titled 'Fixing E4012'. The system uses dense retrieval only.",
        topicIds: ["w14-d02-bm25-hybrid-retrieval"],
        difficulty: "beginner",
        options: [
          "Dense retrieval underweights rare exact tokens; add BM25 (hybrid search)",
          "The page is too long",
          "The LLM ignored the context",
          "The vector index needs more replicas",
        ],
        correct: 0,
        explanation: "Identifiers are rare exact strings that lexical retrieval matches precisely. Hybrid retrieval with rank fusion fixes this class of query.",
      },
      {
        kind: "choice",
        id: "rag-stale-policy",
        title: "Last year's policy",
        prompt: "The bot cites a travel policy that was replaced in March. Both versions are in the index, and the old one scores slightly higher for many queries.",
        topicIds: ["w14-d01-chunking-ingestion", "w14-d03-rag-evaluation"],
        difficulty: "beginner",
        options: [
          "Add 'use the newest document' to the prompt",
          "Increase top-k",
          "Version and effective-date metadata with tombstones, and filter retrieval to current versions",
          "Switch to a larger LLM",
        ],
        correct: 2,
        explanation: "Freshness is a data problem: remove or filter superseded documents at retrieval time. Prompt instructions are unreliable for this.",
      },
      {
        kind: "choice",
        id: "rag-hallucinated-detail",
        title: "Right pages, wrong answer",
        prompt: "Evaluation shows recall@5 of 0.96, but 15% of answers include details (dates, amounts) not present in any retrieved chunk.",
        topicIds: ["w14-d03-rag-evaluation"],
        difficulty: "intermediate",
        options: [
          "Retrieval is broken; rebuild the index",
          "Generation is not grounded; tighten instructions to answer only from context, require citations per claim, and add a groundedness check",
          "Chunks are too small",
          "BM25 parameters are wrong",
        ],
        correct: 1,
        explanation: "High recall with unsupported claims points at generation. Measure groundedness per claim and gate or retry ungrounded answers.",
      },
      {
        kind: "choice",
        id: "rag-injection",
        title: "The document that gave orders",
        prompt: "After a vendor uploaded a PDF, the assistant started appending a link to a third-party site in every answer about invoices. The PDF contains white-on-white text addressed to 'the AI assistant'.",
        topicIds: ["w14-d03-rag-evaluation", "w15-d03-guardrails-budgets-tracing"],
        difficulty: "intermediate",
        options: [
          "A tokenizer bug",
          "Indirect prompt injection through retrieved content; treat retrieved text as data, sanitize ingestion and restrict what outputs can do",
          "The embedding model memorized the link",
          "Cache poisoning in the CDN",
        ],
        correct: 1,
        explanation: "Retrieved text was treated as instructions. Defenses: strip hidden text at ingestion, separate instructions from data, constrain outputs (for example link allowlists) and test with injection cases.",
      },
      {
        kind: "choice",
        id: "rag-permissions",
        title: "A summary nobody should see",
        prompt: "A contractor received a summary of an executive compensation document. The system retrieves top-10 chunks, generates an answer, then removes citations the user cannot access.",
        topicIds: ["w14-d02-bm25-hybrid-retrieval"],
        difficulty: "intermediate",
        options: [
          "Permissions are applied after generation, so restricted content already shaped the answer; filter by access before retrieval ranking",
          "The contractor had admin rights",
          "The LLM provider leaked the data",
          "Top-k is too large",
        ],
        correct: 0,
        explanation: "Access control must happen at retrieval time (document-level ACL filters in the index query), never as a post-processing step on generated text.",
      },
      {
        kind: "choice",
        id: "rag-reindex",
        title: "Quality collapsed after an upgrade",
        prompt: "The team switched to a newer embedding model for queries. Overnight, retrieval quality dropped sharply for every query type.",
        topicIds: ["w14-d02-bm25-hybrid-retrieval", "w13-d01-tokenization-embeddings"],
        difficulty: "beginner",
        options: [
          "The new model is worse",
          "Query and document embeddings come from different models and live in different spaces; re-embed the corpus",
          "The index needs vacuuming",
          "Chunk overlap is too small",
        ],
        correct: 1,
        explanation: "Embeddings from different models are not comparable. Re-embed the corpus with the new model (often as a blue-green index) before switching queries.",
      },
      {
        kind: "choice",
        id: "rag-lost-in-middle",
        title: "Twenty chunks, wrong one used",
        prompt: "To improve recall, the team now sends 20 chunks to the model. Recall improved, but answers got worse, often ignoring the relevant chunk placed in the middle of the context.",
        topicIds: ["w14-d03-rag-evaluation"],
        difficulty: "advanced",
        options: [
          "Long contexts dilute attention; rerank and send fewer, better chunks with the best ones at the start or end",
          "The model's context window is too small",
          "BM25 should be removed",
          "Temperature should be raised",
        ],
        correct: 0,
        explanation: "Models often use information at the start and end of long contexts better than the middle. A reranker plus a smaller, well-ordered context usually beats more chunks.",
      },
    ],
  },
];
