import type { ProjectInput } from "@/lib/content-types";

export const projects: ProjectInput[] = [
  {
    id: "sde-url-shortener",
    role: "sde",
    title: "Production-grade URL shortener",
    summary: "A small service built like a real one: API, persistence, caching, rate limiting, tests, load tests and dashboards.",
    user: "A marketing team creating branded short links for campaigns.",
    decision: "Whether the service can safely take campaign traffic at the stated peak.",
    metric: "p99 redirect latency and error rate at a target peak RPS from your own load test.",
    baseline: "A single process with a database lookup per redirect and no cache.",
    data: [{ name: "Synthetic traffic", note: "Generate with a load-testing tool such as k6 or Locust; document the traffic model you assume." }],
    milestones: [
      { title: "API and storage", deliverable: "Create and redirect endpoints with idempotent creation, input validation and unit tests in CI." },
      { title: "Performance", deliverable: "Cache-aside layer, load test report comparing baseline and cached p99 latency." },
      { title: "Hardening", deliverable: "Rate limiting, abuse checks, structured logs, a dashboard and a one-page runbook." },
    ],
    rubric: [
      "Estimates traffic and storage and explains design choices with them",
      "Tests cover edge cases (collisions, invalid URLs, retries)",
      "Load test shows a measured improvement over the baseline",
      "Failure modes and runbook are documented",
    ],
    stretch: ["Multi-region read replicas with a failover drill", "Click analytics through a queue"],
    topicIds: ["w10-d01-estimation-api-design", "w10-d02-caching-load-balancing", "w03-d02-sliding-window", "w01-d03-testing-reproducibility"],
    weeks: 2,
  },
  {
    id: "sde-job-scheduler",
    role: "sde",
    title: "Job scheduler with retries and exactly-once effects",
    summary: "A background job system with dependencies, retries, idempotent workers and observability.",
    user: "Engineers who need reliable background jobs (emails, exports, cleanups).",
    decision: "Whether jobs can be trusted to run once, in order, despite crashes.",
    metric: "Duplicate side effects and lost jobs under injected worker crashes (target: zero of each).",
    baseline: "A cron loop that runs jobs inline with no retries.",
    data: [{ name: "Synthetic job workloads", note: "Generate job graphs and inject failures with a test harness you write." }],
    milestones: [
      { title: "Core queue", deliverable: "Persistent job table, worker pool, retries with exponential backoff and a dead-letter state." },
      { title: "Dependencies", deliverable: "Topological ordering of job graphs with cycle detection and clear errors." },
      { title: "Chaos test", deliverable: "Crash-injection test proving idempotency keys prevent duplicate effects; metrics and traces." },
    ],
    rubric: [
      "Correct dependency ordering and cycle detection",
      "Idempotency proven with an automated crash test",
      "Backoff, dead-letter handling and visibility timeouts",
      "Clear metrics: queue depth, age of oldest job, failure rate",
    ],
    stretch: ["Cron-style schedules with time zones", "Priority queues with fairness between tenants"],
    topicIds: ["w04-d02-graph-traversal", "w10-d03-replication-queues", "w04-d01-stacks-queues-heaps"],
    weeks: 2,
  },
  {
    id: "ds-experiment-readout",
    role: "data-scientist",
    title: "Experiment analysis toolkit and decision memo",
    summary: "A reusable analysis package (Python or R) for A/B tests, validated on simulations with known effects, plus a decision memo.",
    user: "A product team running weekly A/B tests.",
    decision: "Ship, iterate or stop for a feature test.",
    metric: "Coverage of 95% intervals and false positive rate on simulated A/A and A/B tests (targets about 95% and 5%).",
    baseline: "Comparing raw conversion rates on a dashboard without tests.",
    data: [{ name: "Simulated experiments", note: "Generate data with known true effects so you can prove the methods recover them; state the simulation settings." }],
    milestones: [
      { title: "Core tests", deliverable: "Two-proportion test, intervals, power calculator and sample ratio mismatch check, with unit tests." },
      { title: "Validation", deliverable: "Simulation study of coverage and false positive rate, including the effect of peeking." },
      { title: "Decision memo", deliverable: "A one-page readout template applied to one simulated launch, with guardrail metrics." },
    ],
    rubric: [
      "Methods validated on A/A tests with the expected false positive rate",
      "Power analysis drives the planned sample size",
      "Sample ratio mismatch and peeking are handled explicitly",
      "Memo leads with the decision and its uncertainty",
    ],
    stretch: ["CUPED variance reduction", "A Bayesian readout with expected loss"],
    topicIds: ["w05-d02-hypothesis-testing", "w05-d03-ab-test-power", "w05-d04-bayesian-ab"],
    weeks: 2,
  },
  {
    id: "ds-churn-survival",
    role: "data-scientist",
    title: "Churn analysis with survival curves and a retention recommendation",
    summary: "Survival analysis of subscription churn by segment, with a recommendation the business can act on.",
    user: "A subscription business's retention team.",
    decision: "Which customer segment to target with a retention offer first.",
    metric: "Median survival and 6-month retention by segment, with intervals, and an estimated value of the recommendation.",
    baseline: "Average tenure of churned customers (which ignores censoring).",
    data: [{ name: "IBM Telco Customer Churn sample dataset", note: "A widely mirrored public sample (for example on Kaggle); confirm the license of the copy you use." }],
    milestones: [
      { title: "Data audit", deliverable: "Quality report, censoring definition and cohort tables." },
      { title: "Survival analysis", deliverable: "Kaplan-Meier curves by segment, log-rank comparisons and a Cox model with diagnostics." },
      { title: "Recommendation", deliverable: "A memo recommending one segment and an experiment design to test the offer." },
    ],
    rubric: [
      "Handles censoring correctly and explains why",
      "Compares segments with appropriate tests and intervals",
      "Separates prediction from causal claims and proposes an experiment",
      "Clear, honest limitations",
    ],
    stretch: ["Uplift modeling on a simulated offer", "An interactive report in Quarto or Shiny"],
    topicIds: ["w08-d04-kaplan-meier-survival", "w06-d03-cohort-retention", "w08-d03-causal-inference"],
    weeks: 2,
  },
  {
    id: "mle-taxi-eta",
    role: "ml-engineer",
    title: "Trip duration model with serving and drift monitoring",
    summary: "An end-to-end ML service: time-aware training, a model API, a canary-style rollout and drift monitoring.",
    user: "A dispatch team that needs trip time estimates.",
    decision: "Whether a new model version is safe to promote.",
    metric: "MAE on a later time period versus a baseline, p95 serving latency, and PSI of key features over time.",
    baseline: "Median duration by pickup zone and hour.",
    data: [
      { name: "NYC TLC Trip Record Data", url: "https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page", note: "Public trip records; use a few months and keep the last month as an untouched test period." },
    ],
    milestones: [
      { title: "Training pipeline", deliverable: "Time-based split, leakage checks, baseline and a gradient-boosted model with a reproducible pipeline." },
      { title: "Serving", deliverable: "A containerized prediction API with input validation, latency tests and a model registry entry." },
      { title: "Operations", deliverable: "PSI drift report by month, a promotion gate comparing candidate and current models, and a dashboard." },
    ],
    rubric: [
      "No leakage: time split and features available at prediction time",
      "Beats the baseline on a later period",
      "Serving latency measured and within the target",
      "Drift monitoring with an alerting policy",
    ],
    stretch: ["Shadow deployment comparing two models on replayed traffic", "Feature store with point-in-time joins"],
    topicIds: ["w07-d01-splits-and-leakage", "w07-d04-trees-boosting", "w12-d01-cicd-canary", "w12-d03-drift-observability"],
    weeks: 2,
  },
  {
    id: "mle-recsys",
    role: "ml-engineer",
    title: "Movie recommender with offline evaluation",
    summary: "Candidate generation and ranking with time-respecting evaluation and a recommendations API.",
    user: "Users browsing a catalog who want relevant suggestions.",
    decision: "Which recommender variant to put in front of users.",
    metric: "Recall@10 and NDCG@10 on a time-based holdout, plus catalog coverage.",
    baseline: "Most popular movies in the training period.",
    data: [{ name: "MovieLens datasets (GroupLens)", url: "https://grouplens.org/datasets/movielens/", note: "Use a small or 1M version; respect the dataset's terms of use." }],
    milestones: [
      { title: "Baselines", deliverable: "Popularity and item-item similarity baselines with a time-based split." },
      { title: "Model", deliverable: "Matrix factorization or two-tower embeddings with nearest-neighbor retrieval." },
      { title: "Serving", deliverable: "An API returning top-10 for a user, with cold-start handling and evaluation report." },
    ],
    rubric: [
      "Time-based evaluation without leakage",
      "Beats the popularity baseline on ranking metrics",
      "Handles cold-start users and items",
      "Discusses popularity bias and coverage",
    ],
    stretch: ["A reranker using item metadata", "Exploration with a simple bandit simulation"],
    topicIds: ["w08-d01-clustering-pca", "w14-d03-rag-evaluation", "w13-d01-tokenization-embeddings"],
    weeks: 2,
  },
  {
    id: "genai-docs-rag",
    role: "genai-engineer",
    title: "Documentation assistant with a RAG evaluation suite",
    summary: "A retrieval-augmented assistant over public technical documentation, with hybrid retrieval, citations and an evaluation gate.",
    user: "Developers asking how-to questions about a library.",
    decision: "Whether a change to chunking, retrieval or prompts improves answers enough to ship.",
    metric: "Recall@5, groundedness and answer correctness on a labeled question set, plus cost and latency per answer.",
    baseline: "BM25 retrieval with fixed-size chunks and a simple prompt.",
    data: [{ name: "Python documentation", url: "https://docs.python.org/3/", note: "Public documentation; download the HTML or text build and record the version you indexed." }],
    milestones: [
      { title: "Ingestion and baseline", deliverable: "Section-aware chunking with metadata, BM25 baseline and a 100-question labeled eval set." },
      { title: "Hybrid retrieval", deliverable: "Dense plus BM25 with rank fusion and a reranker, with eval deltas reported." },
      { title: "Generation and gate", deliverable: "Cited answers, a groundedness check, refusal for out-of-scope questions and a CI eval gate." },
    ],
    rubric: [
      "Labeled eval set with retrieval and generation metrics reported separately",
      "Measured improvement over the BM25 baseline",
      "Citations and correct refusals",
      "Cost and latency tracked per answer",
    ],
    stretch: ["Prompt-injection test cases in the eval suite", "Incremental re-ingestion on doc updates"],
    topicIds: ["w14-d01-chunking-ingestion", "w14-d02-bm25-hybrid-retrieval", "w14-d03-rag-evaluation", "w13-d03-decoding-structured-output"],
    weeks: 2,
  },
  {
    id: "genai-agent-triage",
    role: "genai-engineer",
    title: "Issue triage agent with tools, approvals and tracing",
    summary: "An agent that labels and drafts responses to open-source issues using tools, with human approval for any write action.",
    user: "Maintainers of an open-source repository.",
    decision: "Whether automated triage saves maintainer time without harmful actions.",
    metric: "Label accuracy on a held-out set of past issues, maintainer approval rate of drafts, and zero unapproved write actions.",
    baseline: "Keyword rules for labels and no drafted responses.",
    data: [{ name: "Public GitHub issues via the GitHub REST API", url: "https://docs.github.com/en/rest", note: "Use a public repository; respect rate limits and do not post anything without maintainer approval." }],
    milestones: [
      { title: "Workflow first", deliverable: "A deterministic triage workflow with an LLM classification step and an evaluation on past issues." },
      { title: "Tools", deliverable: "Typed tools (search issues, read docs, propose labels) with budgets and full tracing." },
      { title: "Guardrails", deliverable: "Approval gate for all write actions, injection tests on issue text, and a trace review report." },
    ],
    rubric: [
      "Starts with a workflow and justifies any agentic step",
      "Tools are typed, scoped and budgeted",
      "Write actions require approval enforced in code",
      "Traces and an evaluation report on real past issues",
    ],
    stretch: ["Duplicate-issue detection with embeddings", "Cost dashboard per triaged issue"],
    topicIds: ["w15-d01-workflows-vs-agents", "w15-d02-tools-planning-memory", "w15-d03-guardrails-budgets-tracing"],
    weeks: 2,
  },
  {
    id: "de-lakehouse",
    role: "data-engineer",
    title: "Trip data lakehouse with incremental loads and quality gates",
    summary: "An ELT pipeline that lands raw files, builds modeled tables incrementally, and blocks bad data with contracts.",
    user: "Analysts who need trustworthy daily trip metrics.",
    decision: "Whether today's data is safe to publish to dashboards.",
    metric: "Freshness, quality-check pass rate and runtime per daily load; zero published batches with failed error-level checks.",
    baseline: "A full reload script with no checks.",
    data: [
      { name: "NYC TLC Trip Record Data", url: "https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page", note: "Monthly Parquet files make a realistic incremental source." },
    ],
    milestones: [
      { title: "Landing and modeling", deliverable: "Raw Parquet landing, a star schema with a zone dimension, and partitioned fact tables." },
      { title: "Incremental and quality", deliverable: "Incremental MERGE loads, data contracts with error and warn severities, and write-audit-publish." },
      { title: "Orchestration", deliverable: "A DAG with backfills, lineage documentation and a freshness dashboard." },
    ],
    rubric: [
      "Correct incremental logic with idempotent reruns",
      "Contracts that block bad batches before publish",
      "Partitioning and file sizes justified by query patterns",
      "Backfill and lineage documented",
    ],
    stretch: ["SCD Type 2 on a slowly changing reference table", "Cost report per pipeline run"],
    topicIds: ["w11-d01-etl-elt-cdc", "w11-d02-formats-spark-shuffle", "w11-d04-data-quality-orchestration", "w02-d03-scd2-dimensions"],
    weeks: 2,
  },
  {
    id: "de-streaming",
    role: "data-engineer",
    title: "Streaming aggregates with watermarks and late data",
    summary: "A streaming job that computes per-minute aggregates from a public event stream, with correct late-data handling.",
    user: "An operations team watching live activity.",
    decision: "Whether real-time numbers are accurate enough to act on.",
    metric: "Difference between streaming and batch-recomputed totals, late-event rate and end-to-end latency.",
    baseline: "Processing-time windows with no watermark.",
    data: [{ name: "Wikimedia EventStreams recent-changes feed", note: "A public server-sent events stream of wiki edits; check its usage guidelines before connecting." }],
    milestones: [
      { title: "Ingest", deliverable: "A consumer writing events to a log or files with schemas and replay ability." },
      { title: "Windows", deliverable: "Event-time tumbling windows with a watermark, side output for late events and metrics." },
      { title: "Reconcile", deliverable: "A batch job recomputing exact totals and a report comparing streaming and batch numbers." },
    ],
    rubric: [
      "Event-time semantics with a justified watermark",
      "Late events counted and reconciled, not silently dropped",
      "Replayable ingestion",
      "Latency and accuracy both measured",
    ],
    stretch: ["Exactly-once sink with transactions", "Anomaly alerts on the aggregates"],
    topicIds: ["w11-d03-streaming-windows", "w11-d01-etl-elt-cdc", "w08-d02-anomaly-forecasting"],
    weeks: 2,
  },
  {
    id: "da-kpi-dashboard",
    role: "data-analyst",
    title: "KPI dashboard with a metric tree and weekly root-cause notes",
    summary: "A self-serve dashboard for an online store's revenue, built on a documented metric tree, with a repeatable process for explaining week-over-week changes.",
    user: "A commercial team that reviews performance every Monday.",
    decision: "Where to focus next week: traffic, conversion, order value, or a specific segment.",
    metric: "Share of weekly revenue changes explained by named drivers (target: the residual is under 10% of the change), and time to produce the Monday note.",
    baseline: "A single revenue line chart with no breakdown, explained ad hoc in meetings.",
    data: [
      { name: "Public e-commerce transactions", note: "Use an openly licensed online retail dataset (invoices, products, customers, countries, dates); check the license and document cleaning steps." },
    ],
    milestones: [
      { title: "Model and quality checks", deliverable: "A clean orders table at a stated grain, with tests for duplicates, missing ids, negative amounts and late-arriving rows." },
      { title: "Metric tree and dashboard", deliverable: "Revenue = sessions × conversion × average order value, by week and segment, with honest charts and definitions on the page." },
      { title: "Root-cause routine", deliverable: "A SQL or Python script that decomposes a week's change into drivers and segments, plus a one-page Monday note template." },
    ],
    rubric: [
      "Every metric has a written definition, owner and grain",
      "Charts start bars at zero and label units; no dual axes",
      "Driver decomposition sums to the total change (residual shown)",
      "The weekly note leads with the decision and its uncertainty",
    ],
    stretch: ["Alerting when a segment moves more than its usual range", "RFM segments shown alongside the tree"],
    topicIds: ["w06-d02-kpi-root-cause", "w06-d04-visualization-storytelling", "w06-d01-data-quality-eda", "w02-d02-window-functions"],
    weeks: 2,
  },
  {
    id: "da-funnel-retention",
    role: "data-analyst",
    title: "Funnel, cohort retention and an experiment readout",
    summary: "An end-to-end product analysis: an ordered signup funnel, weekly cohort retention, and the readout of a simulated onboarding experiment.",
    user: "A product manager deciding whether to roll out a new onboarding flow.",
    decision: "Roll out, iterate or stop the new onboarding flow.",
    metric: "Activation rate within 7 days of signup (primary) with week-4 retention and support tickets as guardrails.",
    baseline: "Overall signup counts with no ordering, cohorts or statistical testing.",
    data: [{ name: "Simulated product events", note: "Generate users and events with a known true effect so you can check that your analysis recovers it; document the simulation." }],
    milestones: [
      { title: "Funnel", deliverable: "An ordered funnel in SQL with step and overall conversion, robust to out-of-order events." },
      { title: "Cohorts", deliverable: "A weekly cohort retention table that marks future cells as not yet observed." },
      { title: "Readout", deliverable: "A two-proportion test with a confidence interval, a power check, guardrails and a one-page recommendation." },
    ],
    rubric: [
      "Funnel counts only steps completed in order",
      "Retention excludes periods that have not happened yet",
      "The readout states effect size with an interval, not only a p-value",
      "Guardrails and sample ratio are checked before recommending",
    ],
    stretch: ["Segment results by acquisition channel with a multiple-testing correction", "A Bayesian probability that the new flow is better"],
    topicIds: ["w06-d02-metrics-funnels", "w06-d03-cohort-retention", "w05-d02-hypothesis-testing", "w05-d03-ab-test-power"],
    weeks: 2,
  },
];
